New-NetFirewallRule -DisplayName "Block.MSFT.1" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.128.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.2" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.144.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.3" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.160.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.4" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.176.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.5" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.192.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.6" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.208.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.7" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.224.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.8" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.240.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.9" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 13.64.0.0/11
New-NetFirewallRule -DisplayName "Block.MSFT.10" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 13.96.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.11" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 13.104.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.12" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.0.0.0/11
New-NetFirewallRule -DisplayName "Block.MSFT.13" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.33.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.14" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.34.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.15" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.36.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.16" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.40.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.17" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.48.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.18" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.64.0.0/10
New-NetFirewallRule -DisplayName "Block.MSFT.19" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.128.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.20" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.130.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.21" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.135.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.22" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.136.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.23" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.140.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.24" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.143.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.25" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.144.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.26" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.150.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.27" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.152.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.28" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.153.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.29" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.157.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.30" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.160.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.31" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.176.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.32" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.180.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.33" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.184.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.34" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.192.0.0/10
New-NetFirewallRule -DisplayName "Block.MSFT.35" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 23.96.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.36" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 40.64.0.0/10
New-NetFirewallRule -DisplayName "Block.MSFT.37" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 42.159.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.38" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.4.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.39" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.8.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.40" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.10.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.41" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.12.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.42" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.18.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.43" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.51.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.44" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.53.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.45" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.103.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.46" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.104.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.47" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.107.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.48" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.116.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.49" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.120.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.50" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.124.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.51" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.132.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.52" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.136.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.53" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.138.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.54" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.140.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.55" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.144.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.56" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.96.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.57" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.112.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.58" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.120.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.59" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.125.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.60" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.126.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.61" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.130.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.62" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.132.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.63" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.136.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.64" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.145.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.65" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.146.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.66" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.148.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.67" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.152.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.68" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.160.0.0/11
New-NetFirewallRule -DisplayName "Block.MSFT.69" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.224.0.0/11
New-NetFirewallRule -DisplayName "Block.MSFT.70" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 64.4.0.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.71" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 65.52.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.72" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 66.119.144.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.73" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.18.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.74" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.154.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.75" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.210.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.76" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.218.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.77" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.220.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.78" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 70.37.0.0/17
New-NetFirewallRule -DisplayName "Block.MSFT.79" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 70.37.128.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.80" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 70.152.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.81" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 70.156.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.82" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 72.144.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.83" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 72.152.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.84" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.160.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.85" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.176.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.86" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.224.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.87" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.234.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.88" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.240.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.89" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.248.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.90" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 91.190.216.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.91" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 94.245.64.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.92" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 98.64.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.93" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 98.70.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.94" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 102.37.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.95" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 102.133.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.96" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.9.8.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.97" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.25.156.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.98" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.25.157.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.99" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.25.158.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.100" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.36.96.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.101" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.255.140.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.102" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 104.40.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.103" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 104.146.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.104" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 104.208.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.105" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 108.140.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.106" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 111.221.16.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.107" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 111.221.64.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.108" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 128.94.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.109" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 129.75.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.110" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.107.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.111" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.1.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.112" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.3.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.113" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.5.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.114" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.6.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.115" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.8.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.116" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.12.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.117" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.16.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.118" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.18.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.119" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.21.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.120" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.22.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.121" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.24.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.122" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.32.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.123" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.61.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.124" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.62.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.125" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.64.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.126" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.128.0/17
New-NetFirewallRule -DisplayName "Block.MSFT.127" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 132.245.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.128" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 134.170.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.129" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 134.177.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.130" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 135.149.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.131" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 137.116.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.132" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 137.135.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.133" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 138.91.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.134" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 138.196.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.135" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 138.239.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.136" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 139.217.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.137" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 139.219.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.138" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 141.251.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.139" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 143.64.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.140" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 146.147.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.141" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 147.145.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.142" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 147.243.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.143" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 148.7.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.144" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 150.171.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.145" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 150.242.48.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.146" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 155.62.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.147" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 157.54.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.148" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 157.56.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.149" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 157.60.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.150" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 158.158.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.151" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 159.27.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.152" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 163.228.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.153" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 167.105.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.154" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 167.220.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.155" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 168.61.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.156" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 168.62.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.157" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 169.138.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.158" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 170.165.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.159" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 191.232.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.160" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.32.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.161" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.48.225.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.162" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.84.159.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.163" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.84.160.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.164" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.197.157.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.165" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.237.67.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.166" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 193.149.64.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.167" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 193.221.113.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.168" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 194.69.96.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.169" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 194.110.197.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.170" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 195.134.224.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.171" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.105.232.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.172" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.137.97.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.173" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.180.95.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.174" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.180.96.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.175" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.200.130.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.176" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.206.164.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.177" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.30.16.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.178" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.60.28.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.179" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.74.210.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.180" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.103.90.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.181" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.103.122.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.182" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.242.32.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.183" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.242.48.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.184" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 202.89.224.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.185" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.13.120.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.186" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.14.180.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.187" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.135.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.188" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.179.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.189" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.181.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.190" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.188.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.191" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.195.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.192" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.196.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.193" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.252.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.194" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.152.18.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.195" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.152.140.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.196" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.192.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.197" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.194.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.198" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.197.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.199" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.198.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.200" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.200.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.201" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.208.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.202" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.236.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.203" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 205.174.224.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.204" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 206.138.168.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.205" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 206.191.224.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.206" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 207.46.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.207" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 207.68.128.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.208" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 208.68.136.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.209" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 208.76.44.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.210" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 208.84.0.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.211" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 209.240.192.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.212" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 213.199.128.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.213" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 216.32.180.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.214" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 216.220.208.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.215" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:67c:1020::/48
New-NetFirewallRule -DisplayName "Block.MSFT.216" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:df0:7::/48
New-NetFirewallRule -DisplayName "Block.MSFT.217" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:df0:d7::/48
New-NetFirewallRule -DisplayName "Block.MSFT.218" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:df0:d8::/48
New-NetFirewallRule -DisplayName "Block.MSFT.219" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:df0:d9::/48
New-NetFirewallRule -DisplayName "Block.MSFT.220" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:4898::/32
New-NetFirewallRule -DisplayName "Block.MSFT.221" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:489a:2000::/35
New-NetFirewallRule -DisplayName "Block.MSFT.222" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2404:f801::/32
New-NetFirewallRule -DisplayName "Block.MSFT.223" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2602:fd5e::/36
New-NetFirewallRule -DisplayName "Block.MSFT.224" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2603:1000::/24
New-NetFirewallRule -DisplayName "Block.MSFT.225" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2620:0:30::/45
New-NetFirewallRule -DisplayName "Block.MSFT.226" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2620:1ec::/36
New-NetFirewallRule -DisplayName "Block.MSFT.227" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2801:80:1d0::/48
New-NetFirewallRule -DisplayName "Block.MSFT.228" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2a01:110::/32
New-NetFirewallRule -DisplayName "Block.MSFT.229" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2a01:111::/32
New-NetFirewallRule -DisplayName "Block.MSFT.230" -Direction Outbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2a01:4180::/32
New-NetFirewallRule -DisplayName "Block.MSFT.1" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.128.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.2" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.144.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.3" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.160.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.4" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.176.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.5" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.192.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.6" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.208.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.7" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.224.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.8" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 4.240.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.9" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 13.64.0.0/11
New-NetFirewallRule -DisplayName "Block.MSFT.10" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 13.96.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.11" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 13.104.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.12" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.0.0.0/11
New-NetFirewallRule -DisplayName "Block.MSFT.13" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.33.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.14" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.34.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.15" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.36.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.16" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.40.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.17" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.48.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.18" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.64.0.0/10
New-NetFirewallRule -DisplayName "Block.MSFT.19" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.128.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.20" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.130.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.21" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.135.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.22" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.136.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.23" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.140.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.24" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.143.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.25" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.144.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.26" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.150.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.27" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.152.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.28" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.153.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.29" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.157.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.30" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.160.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.31" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.176.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.32" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.180.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.33" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.184.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.34" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 20.192.0.0/10
New-NetFirewallRule -DisplayName "Block.MSFT.35" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 23.96.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.36" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 40.64.0.0/10
New-NetFirewallRule -DisplayName "Block.MSFT.37" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 42.159.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.38" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.4.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.39" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.8.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.40" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.10.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.41" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.12.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.42" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.18.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.43" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.51.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.44" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.53.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.45" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.103.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.46" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.104.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.47" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.107.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.48" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.116.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.49" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.120.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.50" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.124.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.51" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.132.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.52" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.136.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.53" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.138.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.54" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.140.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.55" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 51.144.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.56" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.96.0.0/12
New-NetFirewallRule -DisplayName "Block.MSFT.57" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.112.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.58" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.120.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.59" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.125.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.60" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.126.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.61" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.130.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.62" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.132.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.63" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.136.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.64" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.145.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.65" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.146.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.66" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.148.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.67" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.152.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.68" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.160.0.0/11
New-NetFirewallRule -DisplayName "Block.MSFT.69" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 52.224.0.0/11
New-NetFirewallRule -DisplayName "Block.MSFT.70" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 64.4.0.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.71" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 65.52.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.72" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 66.119.144.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.73" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.18.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.74" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.154.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.75" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.210.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.76" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.218.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.77" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 68.220.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.78" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 70.37.0.0/17
New-NetFirewallRule -DisplayName "Block.MSFT.79" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 70.37.128.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.80" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 70.152.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.81" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 70.156.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.82" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 72.144.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.83" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 72.152.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.84" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.160.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.85" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.176.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.86" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.224.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.87" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.234.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.88" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.240.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.89" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 74.248.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.90" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 91.190.216.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.91" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 94.245.64.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.92" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 98.64.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.93" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 98.70.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.94" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 102.37.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.95" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 102.133.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.96" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.9.8.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.97" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.25.156.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.98" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.25.157.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.99" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.25.158.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.100" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.36.96.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.101" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 103.255.140.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.102" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 104.40.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.103" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 104.146.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.104" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 104.208.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.105" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 108.140.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.106" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 111.221.16.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.107" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 111.221.64.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.108" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 128.94.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.109" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 129.75.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.110" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.107.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.111" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.1.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.112" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.3.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.113" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.5.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.114" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.6.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.115" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.8.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.116" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.12.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.117" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.16.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.118" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.18.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.119" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.21.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.120" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.22.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.121" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.24.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.122" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.32.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.123" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.61.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.124" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.62.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.125" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.64.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.126" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 131.253.128.0/17
New-NetFirewallRule -DisplayName "Block.MSFT.127" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 132.245.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.128" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 134.170.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.129" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 134.177.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.130" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 135.149.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.131" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 137.116.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.132" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 137.135.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.133" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 138.91.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.134" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 138.196.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.135" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 138.239.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.136" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 139.217.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.137" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 139.219.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.138" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 141.251.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.139" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 143.64.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.140" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 146.147.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.141" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 147.145.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.142" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 147.243.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.143" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 148.7.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.144" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 150.171.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.145" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 150.242.48.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.146" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 155.62.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.147" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 157.54.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.148" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 157.56.0.0/14
New-NetFirewallRule -DisplayName "Block.MSFT.149" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 157.60.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.150" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 158.158.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.151" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 159.27.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.152" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 163.228.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.153" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 167.105.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.154" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 167.220.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.155" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 168.61.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.156" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 168.62.0.0/15
New-NetFirewallRule -DisplayName "Block.MSFT.157" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 169.138.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.158" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 170.165.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.159" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 191.232.0.0/13
New-NetFirewallRule -DisplayName "Block.MSFT.160" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.32.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.161" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.48.225.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.162" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.84.159.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.163" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.84.160.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.164" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.197.157.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.165" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 192.237.67.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.166" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 193.149.64.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.167" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 193.221.113.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.168" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 194.69.96.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.169" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 194.110.197.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.170" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 195.134.224.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.171" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.105.232.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.172" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.137.97.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.173" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.180.95.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.174" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.180.96.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.175" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.200.130.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.176" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 198.206.164.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.177" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.30.16.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.178" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.60.28.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.179" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.74.210.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.180" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.103.90.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.181" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.103.122.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.182" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.242.32.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.183" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 199.242.48.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.184" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 202.89.224.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.185" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.13.120.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.186" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.14.180.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.187" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.135.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.188" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.179.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.189" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.181.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.190" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.188.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.191" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.195.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.192" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.196.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.193" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.79.252.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.194" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.152.18.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.195" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.152.140.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.196" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.192.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.197" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.194.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.198" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.197.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.199" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.198.0/23
New-NetFirewallRule -DisplayName "Block.MSFT.200" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.200.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.201" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.208.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.202" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 204.231.236.0/24
New-NetFirewallRule -DisplayName "Block.MSFT.203" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 205.174.224.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.204" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 206.138.168.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.205" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 206.191.224.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.206" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 207.46.0.0/16
New-NetFirewallRule -DisplayName "Block.MSFT.207" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 207.68.128.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.208" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 208.68.136.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.209" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 208.76.44.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.210" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 208.84.0.0/21
New-NetFirewallRule -DisplayName "Block.MSFT.211" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 209.240.192.0/19
New-NetFirewallRule -DisplayName "Block.MSFT.212" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 213.199.128.0/18
New-NetFirewallRule -DisplayName "Block.MSFT.213" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 216.32.180.0/22
New-NetFirewallRule -DisplayName "Block.MSFT.214" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 216.220.208.0/20
New-NetFirewallRule -DisplayName "Block.MSFT.215" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:67c:1020::/48
New-NetFirewallRule -DisplayName "Block.MSFT.216" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:df0:7::/48
New-NetFirewallRule -DisplayName "Block.MSFT.217" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:df0:d7::/48
New-NetFirewallRule -DisplayName "Block.MSFT.218" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:df0:d8::/48
New-NetFirewallRule -DisplayName "Block.MSFT.219" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:df0:d9::/48
New-NetFirewallRule -DisplayName "Block.MSFT.220" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:4898::/32
New-NetFirewallRule -DisplayName "Block.MSFT.221" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2001:489a:2000::/35
New-NetFirewallRule -DisplayName "Block.MSFT.222" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2404:f801::/32
New-NetFirewallRule -DisplayName "Block.MSFT.223" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2602:fd5e::/36
New-NetFirewallRule -DisplayName "Block.MSFT.224" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2603:1000::/24
New-NetFirewallRule -DisplayName "Block.MSFT.225" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2620:0:30::/45
New-NetFirewallRule -DisplayName "Block.MSFT.226" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2620:1ec::/36
New-NetFirewallRule -DisplayName "Block.MSFT.227" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2801:80:1d0::/48
New-NetFirewallRule -DisplayName "Block.MSFT.228" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2a01:110::/32
New-NetFirewallRule -DisplayName "Block.MSFT.229" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2a01:111::/32
New-NetFirewallRule -DisplayName "Block.MSFT.230" -Direction Inbound -LocalPort Any -Protocol Any -Action Block -RemoteAddress 2a01:4180::/32
