Remove-NetFirewallRule -DisplayName "Block.MSFT.1" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.2" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.3" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.4" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.5" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.6" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.7" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.8" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.9" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.10" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.11" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.12" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.13" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.14" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.15" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.16" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.17" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.18" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.19" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.20" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.21" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.22" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.23" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.24" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.25" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.26" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.27" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.28" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.29" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.30" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.31" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.32" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.33" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.34" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.35" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.36" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.37" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.38" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.39" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.40" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.41" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.42" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.43" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.44" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.45" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.46" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.47" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.48" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.49" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.50" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.51" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.52" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.53" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.54" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.55" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.56" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.57" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.58" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.59" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.60" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.61" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.62" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.63" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.64" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.65" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.66" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.67" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.68" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.69" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.70" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.71" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.72" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.73" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.74" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.75" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.76" -verbose
Remove-NetFirewallRule -DisplayName ""Block.MSFT.*"" -verbose
Remove-NetFirewallRule -DisplayName ""Block.MSFT.*"78" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.79" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.80" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.81" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.82" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.83" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.84" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.85" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.86" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.87" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.88" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.89" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.90" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.91" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.92" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.93" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.94" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.95" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.96" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.97" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.98" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.99" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.100" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.101" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.102" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.103" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.104" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.105" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.106" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.107" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.108" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.109" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.110" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.111" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.112" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.113" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.114" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.115" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.116" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.117" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.118" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.119" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.120" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.121" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.122" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.123" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.124" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.125" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.126" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.127" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.128" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.129" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.130" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.131" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.132" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.133" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.134" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.135" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.136" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.137" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.138" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.139" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.140" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.141" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.142" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.143" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.144" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.145" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.146" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.147" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.148" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.149" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.150" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.151" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.152" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.153" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.154" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.155" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.156" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.157" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.158" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.159" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.160" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.161" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.162" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.163" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.164" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.165" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.166" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.167" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.168" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.169" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.170" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.171" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.172" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.173" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.174" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.175" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.176" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.177" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.178" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.179" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.180" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.181" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.182" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.183" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.184" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.185" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.186" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.187" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.188" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.189" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.190" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.191" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.192" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.193" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.194" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.195" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.196" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.197" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.198" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.199" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.200" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.201" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.202" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.203" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.204" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.205" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.206" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.207" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.208" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.209" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.210" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.211" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.212" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.213" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.214" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.215" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.216" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.217" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.218" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.219" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.220" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.221" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.222" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.223" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.224" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.225" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.226" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.227" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.228" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.229" -verbose
Remove-NetFirewallRule -DisplayName "Block.MSFT.230" -verbose
